# Generated by Django 5.0.3 on 2024-03-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='born_data',
            new_name='born_date',
        ),
    ]
